[project]
name = "timelock-utility"
authors = ["BlockchainDev"]
description = "A smart contract utility for time-locked token distribution and vesting"
telemetry = false
requirements = []
[contracts.timelock-core]
path = "contracts/timelock-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
